// export const primary = "#2B3A42"
// export const primary2 = "#3F5765"
// export const secondary = "#BDD4DE"
// export const tertiary = "#FF530D"
// export const white = "#EFEFEF"

export const primary = "black"
export const primary2 = "white"
export const secondary = "#35323280"
export const tertiary = "gray"
export const white = "#EFEFEF"