export const FETCH_WEATHER_DATA = "FETCH_WEATHER_DATA"
export const FETCH_WEATHER_DATA_SUCCESS = "FETCH_WEATHER_DATA_SUCCESS"
export const FETCH_WEATHER_DATA_ERROR = "FETCH_WEATHER_DATA_ERROR"
export const SHOW_WEATHER_DATA = "SHOW_WEATHER_DATA"
export const COLLAPSE_FORM = "COLLAPSE_FORM"
export const ANIMATE_FORM_HEIGHT_START = "ANIMATE_FORM_HEIGHT_START"
export const ANIMATE_FORM_HEIGHT_END = "ANIMATE_FORM_HEIGHT_END"
export const FETCH_CURRENT_LOCATION_WEATHER_DATA = "FETCH_CURRENT_LOCATION_WEATHER_DATA"

